/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Mandoline;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.org.apache.xerces.internal.util.DOMUtil;
import java.awt.BorderLayout;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/**
 *
 * @author Mathieu
 */
public class Vue extends javax.swing.JFrame {

    /**
     * Creates new form Player
     */
    public Vue() {
        
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:/Program Files/VideoLAN/VLC");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        mediaPlayerComponent = new EmbeddedMediaPlayerComponent();

        //mediaPlayerComponent.getMediaPlayer().start();
        System.out.println("Created");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pause = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        playList = new ModelPlayList();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });
        getContentPane().add(Pause, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jSlider1, java.awt.BorderLayout.PAGE_END);

        jButton1.setText("jButton1");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout playListLayout = new javax.swing.GroupLayout(playList);
        playList.setLayout(playListLayout);
        playListLayout.setHorizontalGroup(
            playListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playListLayout.setVerticalGroup(
            playListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playListLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getContentPane().add(playList, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        // TODO add your handling code here:
        mediaPlayerComponent.getMediaPlayer().pause();
    }//GEN-LAST:event_PauseActionPerformed




    private EmbeddedMediaPlayerComponent mediaPlayerComponent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pause;
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel playList;
    // End of variables declaration//GEN-END:variables

    
    public void startVideo() {
        add(mediaPlayerComponent,BorderLayout.CENTER);
        //jInternalFrame1.add(mediaPlayerComponent,BorderLayout.CENTER);
        System.out.println("Start video");
        mediaPlayerComponent.getMediaPlayer().playMedia("D:\\le.pacte.avi");
        mediaPlayerComponent.getMediaPlayer().start();
        
        //jSlider1.setValue(75);
        
    }
    
    
}
